version: '3.8'

services:
  video-validator:
    build: .
    container_name: video-validator
    restart: unless-stopped
    ports:
      - "8099:5000"
    volumes:
      - /mnt/user/media/movies:/media/movies:rw
      - /mnt/user/media/tv:/media/tv:rw
      - /mnt/user/appdata/video-validator/data:/app/data:rw
    user: "99:100"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Budapest

